### ISSUE TITLE
typerrror when running

### ISSUE THREAD

**Issue by emerysteele** [chvolkmann/voicemeeter-remote-python#3]
```
Traceback (most recent call last):
  File "Python\Hom3\vm.py", line 9, in <module>
    with voicemeeter.remote(kind) as vmr:
  File "C:\Users\emery\AppData\Local\Programs\Python\Python38\lib\site-packages\voicemeeter\remote.py", line 135, in __enter__
    self._login()
  File "C:\Users\emery\AppData\Local\Programs\Python\Python38\lib\site-packages\voicemeeter\remote.py", line 34, in _login
    self._call('Login')
  File "C:\Users\emery\AppData\Local\Programs\Python\Python38\lib\site-packages\voicemeeter\remote.py", line 30, in _call
    time.sleep(self.delay)
TypeError: an integer is required (got type NoneType)
```

**Comment by Slasherss1** [comment]
Can you show your code?

**Comment by chvolkmann** [comment]
@emerysteele Please attach a sample of your code and open a new issue.
